### ISSUE TITLE
Make it work on browser

### ISSUE THREAD

**Issue by guicheffer** [alissonperez/deepicker#6]
hey! wanna use on my `jsfiddle` projects, may I? 👀

**Comment by guicheffer** [comment]
pls can you add a `enhancement` label? <3

**Comment by guicheffer** [comment]
cc @alissonperez 

**ps.**1, pls check against label additions into prs and issues (collaborators should be able to do it, not sure if github accepts it)

**Comment by alissonperez** [comment]
yes! nice enhancement @guicheffer , "taca o pau"!
